# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
highlighter:      rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            Tool-Name
tagline:          Tagline for website
description:      "Short description of the tool, for the sidebar"
#url:              https://github.com/saezlab/projectDocumentationTemplate
baseurl:          /projectDocumentationTemplate/

author:
  name:           'Author Name'

paginate:         5

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/saezlab/projectDocumentationTemplate
